### ISSUE TITLE
UAAL Installation

### ISSUE THREAD

**Issue by ClementBrohon** [universAAL/nativeandroid#1]
Hello, 

I follow this tutorial : https://github.com/universAAL/nativeandroid/wiki
And dowload this apk : https://github.com/universAAL/nativeandroid/blob/master/Files/mw.container.android.apk

I install the apk and start the application. I do a mp4 where we see exactly the problem.
But if I have to describe:
- The application don't start alone, the progress bar stay at 0%.
- If I went to setting I noticed the button "enter" is invisible. I click everywhere and it works.
- If I push the button start, the progress bar start. But when it finished, it crash. 

I try to restart the smartphone without alteration. I try to force close.

My phone is a OnePlus 3T, 6GB RAM, 64GB stockage almost all free, android 7.1.1

Thank you
Clément

![bug_uall](https://cloud.githubusercontent.com/assets/25262825/25807186/37d7fc6c-3406-11e7-8df0-61545d49912f.gif)

**Comment by Alfiva** [comment]
It would be helpful to see the output of the Android logcat console while this happens.
Apart from that, Ihave a couple comments:
-I still haven't had the time to test the app with Android 7.1.1. It may be something related to that, I will test when I have some time.
-From the video I see you are not connected to any WiFi network, despite having WiFi enabled (WiFi icon with ?). Can you check again, but disabling the "WiFi discovery" options in uAAL settings?
-Or perhaps you are connected to a WiFi but without internet access (WiFi icon with X) - I haven't seen that icon before... If this is the case please take into account that from Android 5.0 this leads to some problems. Try again with a WiFi with internet access, or with WiFi disabled (see previous comment).

**Comment by ClementBrohon** [comment]
It is wifi without internet access. I have some problems with my connexion, I will try with a wifi networks.

- I try without Wifi discovery and without wifi, and it crashes too
- I try without Wifi discovery and without wifi, and it crashes.
- I try without wifi discovery and with wifi but without network. I have the same result.
- I try with wifi discovery, with wifi but without netwrk (like the video). It takes more time and crashes.

I see this part
"Each uAAL-compatible app will require some ontologies to work with the uAAL app. The uAAL app alredy includes support for the core ontologies (phWorld, unit, measurement, profile) but if your uAAL-compatible apps rely on additional ontologies, you have to add them to the Android device first."

I have just dowload the two exemple "lightClient" and "lightServor" but I force close for these tests. So I have not uAAL-compatible app yet..

I see in data/felix that there are only "configurations" directory, no "ontology" as I expect.


How I can see logs? Do I have to import and install the building source with android Studio?

EDIT: I succeeded to capture all log of my phone. It is hard to read.
I think that it starts from this line "http://ontology.universAAL.org/DataRepresentation.owl (classes: 7)" 
I think this line who explain the problem:
"--------- beginning of crash"

**Comment by Alfiva** [comment]
By looking at your log, I think the lighting example is the issue.
The lighting example apks require the Lighting ontology, which is not inlcuded by default in the uAAL app. You can:
1) Uninstall the lighitng apks and try to see if uAAL starts successfully (Because even if you force-closed the lighting apps, uAAL checks for installed apps, not running ones)
2) Once that works, try adding the *dexed* ontology to the ontologies folder as described by the wiki, creating the ontologies folder if needed (You can find the dexed ontology for lighting here: https://github.com/universAAL/nativeandroid/tree/master/Files/Configurations/felix/ontologies)

**Comment by ClementBrohon** [comment]
It works! :)

Thank you!
