### ISSUE TITLE
error in the tutorial?

### ISSUE THREAD

**Issue by ClementBrohon** [universAAL/nativeandroid#2]
Here:

https://github.com/universAAL/nativeandroid/wiki/Adapting-or-developing-your-app-for-uAAL

In examples "Service Callee" and "Service Caller" I think there are a little error:
```
<replyAction> <! -- INTENT ACTION TO THE MW FOR THE REPLY --> </replyaction>
<replyCategory> <! -- INTENT CATEGORY TO THE MW FOR THE REPLY--> </replycategory>
```

My IDE Android Studio don't want to compile because the two tags are note exactly the same.
replyAction  -> /replyaction
replyCategory -> /replycategory

Clément

**Comment by Alfiva** [comment]
The right way is replyAction at start and end,  and replyCategory at start and end.
But this is weird. In the wiki page source text it is correctly written, but when rendered the page appears all in lower case... I will investigate later, but for know just do it as commented above.
Thanks for the heads up.

**Comment by ClementBrohon** [comment]
And at the end of the same document, in Service Callee I see this exemple:

```
 <receiver android:name=".service.LightService" android:enabled="true" android:exported="true" >
    ...
    <intent-filter>
        <action android:name="org.universaal.nativeandroid.lightserver.GET_CONTROLLED_LAMPS" />
        <category android:name="android.intent.category.DEFAULT" />
    </intent-filter>
 </service>

```
I think the last tag "`</service>`" should be "`</receiver>`"
If I compare with the lightingexemple I have something like this:

```
<receiver
            android:name=".LightReplyReceiver"
            android:enabled="true"
            android:exported="true" >
            <intent-filter>
                <action android:name="org.universaal.nativeandroid.lightmusic.REPLY_GETLAMPS" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </receiver>
```

**Comment by Alfiva** [comment]
Yes that is correct. It is fixed now.

**Comment by Alfiva** [comment]
Could not find a way to fix the lower case closing tag for replyAction and replyCategory, so I included a warning in the wiki.
