### ISSUE TITLE
Ununderstood of the serialization

### ISSUE THREAD

**Issue by ClementBrohon** [universAAL/nativeandroid#3]
Hello, 

I try to understand serialization and  turtle language. For this, I write a little code for switch on a bluetooth lamp.
If I try without uAAL (I put the same sentence on both side, brodcast emiter and recever), it's works. My problem is where I try to communicate through UAAL.

I have two programs. Can you please say me if you see an error?

**## Recever uAAL:**
```
<?xml version="1.0" encoding="utf-8"?>
<application>
    <permissions>
        <mw.bus.service>
        </mw.bus.service>
        <mw.bus.context>
            <requirement>
                <title>Subscribe to PutON</title>
                <description>CONTEXT SUBSCRIBER PATTERN: Receive my button test</description>
                <action>org.universaal.nativeandroid.lightbluetooth.PUT_ON</action>
                <category>android.intent.category.DEFAULT</category>
                <remote>true</remote>
                <output>
                    <key>http://www.w3.org/1999/02/22-rdf-syntax-ns#subject</key>
                    <value>http://ontology.igd.fhg.de/LightingServer.owl#{lamp}</value>
                </output>
                <output>
                    <key>http://www.w3.org/1999/02/22-rdf-syntax-ns#object</key>
                    <value>brightness</value>
                </output>
                <serialization>
                <![CDATA[
                     @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
                     @prefix ns: <http://ontology.universaal.org/Lighting.owl#> .
                     @prefix : <http://www.w3.org/2002/07/owl#> .
                     <http://ontology.igd.fhg.de/LightingServer.owl#cep1> a <http://ontology.universAAL.org/Context.owl#ContextEventPattern> ;
                      <http://www.w3.org/2000/01/rdf-schema#subClassOf> [
                          a :Restriction ;
                          :allValuesFrom ns:LightSource ;
                          :onProperty rdf:subject
                        ] ,
                        [
                          :hasValue ns:srcBrightness ;
                          a :Restriction ;
                          :onProperty rdf:predicate
                        ] ,
                        [
                          a :Restriction ;
                          :allValuesFrom <http://www.w3.org/2001/XMLSchema#int> ;
                          :onProperty rdf:object
                        ] .
                     ns:LightSource a :Class .
                     ]]>
                </serialization>
            </requirement>
            <requirement>
                <title>Subscribe to PutOff</title>
                <description>CONTEXT SUBSCRIBER PATTERN: Receive my button test</description>
                <action>org.universaal.nativeandroid.lightbluetooth.PUT_OFF</action>
                <category>android.intent.category.DEFAULT</category>
                <remote>true</remote>
            </requirement>
        </mw.bus.context>
    </permissions>
</application>

```
**## Recever manifest:**

```
 <receiver
            android:name=".LightCallOnReceiver"
            android:enabled="true"
            android:exported="true" >
            <intent-filter>
                <action android:name="org.universaal.nativeandroid.lightbluetooth.PUT_ON" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </receiver>
```

**## Emiter broadcast function:**

`
public static final String PREFIX = "org.universaal.nativeandroid.forcerUAAL.";
public static final String ACTION_CALL_OFF = PREFIX + "PUT_OFF";

public void onButtonPutON(View v) {
        Intent intent = new Intent(ACTION_CALL_ON);
        intent.addCategory(Intent.CATEGORY_DEFAULT);
        intent.putExtra("org.universaal.nativeandroid.light.lamp", "mylamp1");
        intent.putExtra("org.universaal.nativeandroid.light.brightness", "100");
        sendBroadcast(intent);

        isPaused = (TextView)findViewById(R.id.Pause);
        isPaused.setText("Message envoyé");
    }`

**## Emiter UALL file:**

`<?xml version="1.0" encoding="utf-8"?>
<application>
    <permissions>
        <mw.bus.service>

        </mw.bus.service>
        <mw.bus.context>
            <advertisement>
                <title> PUBLISHER PUBLISHER PUBLISHER </title>
                <description> SERVICE PUBLISHER PROFILE : Send the signal for switch on my lamp</description>
                <action> org.universaal.nativeandroid.forcerUAAL.PUT_ON </action>
                <category> android.intent.category.DEFAULT </category>
                <input>
                    <key>var1</key>
                    <value>lamp</value>
                </input>
                <input>
                    <key>var2</key>
                    <value>brightness</value>
                </input>
                <serialization>
                    <![CDATA[
                        @prefix ph: <http://ontology.universaal.org/PhThing.owl#> .
                        @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
                        @prefix tst: <http://ontology.igd.fhg.de/LightingServer.owl#> .
                        @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
                        @prefix light: <http://ontology.universaal.org/Lighting.owl#> .
                        @prefix ctxt: <http://ontology.universAAL.org/Context.owl#> .
                        @prefix owl: <http://www.w3.org/2002/07/owl#> .

                        <urn:org.universAAL.middleware.context.rdf:ContextEvent#_:c043cf9e99c148f8:be9> ctxt:hasProvider tst:LightServer ;
                          a ctxt:ContextEvent ;
                          rdf:subject tst:&var1;controlledLamp1&var1; ;
                          ctxt:hasTimestamp "1384864157846"^^xsd:long ;
                          rdf:predicate light:srcBrightness ;
                          rdf:object "&var2;100&var2;"^^xsd:int .
                        tst:&var1;controlledLamp1&var1; a light:LightSource ,
                            ph:Device ,
                            ph:PhysicalThing ;
                          light:srcBrightness "&var2;100&var2;"^^xsd:int .
                        ctxt:gauge a ctxt:ContextProviderType .
                        tst:LightServer a ctxt:ContextProvider ;
                          ctxt:hasType ctxt:gauge ;
                          ctxt:myClassesOfEvents [
                              a ctxt:ContextEventPattern ;
                              <http://www.w3.org/2000/01/rdf-schema#subClassOf> [
                                  a owl:Restriction ;
                                  owl:allValuesFrom light:LightSource ;
                                  owl:onProperty rdf:subject
                                ]
                            ] .
                        ]]>
                </serialization>
            </advertisement>

        </mw.bus.context>
    </permissions>
</application>`

Thank you, 
Clément

**Comment by Alfiva** [comment]
I will look further into it as soon as I can. In the meantime, can you see any error message in the Android logcat console? If so, can you attach it?
Very quick comment that may or may not affect: you seem to set the value of {lamp} to "1". Please use a string that starts with a lower case letter, like "mylamp1".

**Comment by ClementBrohon** [comment]
I change for

```
public void onButtonPutON(View v) {
        Intent intent = new Intent("org.universaal.nativeandroid.forcer.puton");
        intent.addCategory(Intent.CATEGORY_DEFAULT);
        intent.putExtra("org.universaal.nativeandroid.light.lamp", "mylamp1");
        intent.putExtra("org.universaal.nativeandroid.light.brightness", "ex100");
        sendBroadcast(intent);

        isPaused = (TextView)findViewById(R.id.Pause);
        isPaused.setText("Message envoyé");
    }
```

There has been no change. I watch the debugger but there's nothing interesting, just "App start" and "stop". I think there are no problem of code because I have no problems where I use just the broadcast emitter. It's when I want to force the use of the universal by writing differents uri "org.universaal.nativeandroid.lightbluetooth.PUT_ON" and "org.universaal.nativeandroid.forcerUAAL.PUT_ON"  that nothing happens . I may fail the setting of the listing or the sends.

In fact I don't know the tools and I have just do a beginner's little error.

**Comment by Alfiva** [comment]
-The uaal file of the emitter looks OK, but just in case make sure you don't have extra blank spaces in action and category

-In the code for sending the event, according to the uaal file of the emitter, it should actually have:
Intent intent = new Intent("org.universaal.nativeandroid.forcerUAAL.PUT_ON");
intent.addCategory(Intent.CATEGORY_DEFAULT);
intent.putExtra("lamp", "mylamp1");
intent.putExtra("brightness", "100");

{Notice that the value for lamp starts with lower case letter, and that brightness must be parseable to an integer (e.g. "ex100" would be wrong).}

-The uaal file of the receiver seems OK. Make sure, before dealing with extras, that you do get an intent in your LightCallOnReceiver.

-For curiosity: Which version of Android are you using? Latest versions impose some restrictions on broadcast receivers, I still need to review those, but I think it shouldn't be a problem...

Please try with the changes suggested above and see if it works (see if at least your LightCallOnReceiver gets called, no matter with what).

**Comment by Alfiva** [comment]
Plus: a little trick I found on developer.android.com:
You can find out if uAAL has properly registered the emitter file if you call intent.resolveActivity() before sending the intent. If it returns null, something was wrong.

**Comment by ClementBrohon** [comment]
It works. A beginner's error:

I put the tag metadata in "activity", I correct that and the function with "mylamp".

For the moment, I have just modified the example, I will try to create my own serialization with device ontology.

Thank you for the help :)
