### ISSUE TITLE
Launch local uAAL server

### ISSUE THREAD

**Issue by acapop** [universAAL/nativeandroid#480]
How can I start local uAAL server?

I tried with karaf 3.0.5 from git repository and 3.4.0. I installed uAAL-MW on my laptop and I coundnt connect to it with uAAL android app. I tried to use gateway in configuration (android phone directly connected to my laptop) and typing in laptop ip address: 192.168.137.1:5005, 192.168.137.1:5005/universaal and few other ports, can someone help me? And its when I try to connect to default server.

Thank you in advance

**Comment by Alfiva** [comment]
Have you followed the instructions in https://github.com/universAAL/nativeandroid/wiki/Running-uAAL-in-Android#Connecting_to_PC ? There are some specific steps to follow to make sure the connection will happen. This is for direct connection between the app and the PC through the same network (no "remote connection" setting).
